<?php
/**
 * Paytype Livesearch Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the PayType EULA (End-user license
 * agreement) that is bundled with this package in the file license.txt.
 * You may not give, sell, distribute, sub-license, rent, lease or lend
 * any portion of the Software or Documentation to anyone. 
 *
 * @category   Paytype
 * @package    Paytype_Livesearch 1.1
 * @author     M.Rivas
 * @copyright  Copyright (c) 2009 Paytype SL (http://magentomodules.paytype.com)
 * @license    End-user license Agreement
 */
?>
<!-- Paytype Livesearch FORM -->
<form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
    <fieldset>
        <legend><?php echo $this->__('Search Site') ?></legend>
        <div class="mini-search">
		<div class="lsloading" id="lsloading" style="display:none; float: right;  position:absolute;top:3px; right: 110px"><?php if (Mage::getStoreConfig('admin/livesearch/loadingicon') == 1): ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"><?php endif; ?></div>
            <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogSearch')->getEscapedQueryText() ?>" onKeyPress="return submitenter(this,event)" />
            <input type="image" src="<?php echo $this->getSkinUrl('images/btn_mini_search.gif') ?>" alt="<?php echo $this->__('Search') ?>" />
	<div id="search_autocomplete" class="search-autocomplete"></div>
            <script type="text/javascript">
            //<![CDATA[
                var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
                searchForm.initLivesearch('<?php echo $this->helper('catalogSearch')->getSuggestUrl() ?>', 'search_autocomplete', <?php echo intval(Mage::getStoreConfig('admin/livesearch/charstostart')) ?>);
		function submitenter(myfield,e)
		{
		var keycode;
		if (window.event) keycode = window.event.keyCode;
		else if (e) keycode = e.which;
		else return true;
		if (keycode == 13)
		   {
		   myfield.form.submit();
		   return false;
		   }
		else
		   return true;
		}
            //]]>
            </script>
        </div>
    </fieldset>
</form>
