<div class="user-info">
<div class="head">
<span><?php echo $this->__('User info').'<br/>' ?></span>
</div>
<ul>
<li><span><?php echo $this->htmlEscape($this->getCustomer()->getFirstname()).' '.$this->htmlEscape($this->getCustomer()->getLastname()).'<br/>' ?></span></li>
<li><span><?php echo $this->htmlEscape($this->getCustomer()->getSex()).'<br/>' ?></span></li>
<li><span><?php echo $this->htmlEscape($this->getCustomer()->getDob()).'<br/>' ?></span></li>
<li><span><?php echo $this->htmlEscape($this->getCustomer()->getEmail()).'<br/>' ?></span></li>
<a href="<?php echo $this->helper('customer/data')->getLogoutUrl() ?>"><?php echo __('Log Out') ?></a>
</ul>
</div>