<?php echo $this->__('Dati Utente').'<br/>' ?>
<?php echo $this->htmlEscape($this->getCustomer()->getFirstname()).' '.$this->htmlEscape($this->getCustomer()->getLastname()).'<br/>' ?>
<?php echo $this->htmlEscape($this->getCustomer()->getSex()).'<br/>' ?>
<?php echo $this->htmlEscape($this->getCustomer()->getDob()).'<br/>' ?>
<?php echo $this->htmlEscape($this->getCustomer()->getEmail()).'<br/>' ?>