<ul>
  <li>
    <?php echo $this->__('STATO SPEDIZIONI'); ?>  >
  </li>
  <li>
    <?php echo $this->getLayout()->getBlock("top.links.cart")->toHtml(); ?>
  </li>
    <?php if( $this->getIsSubscribed() ): ?>
      <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
    <?php else: ?>
      <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
    <?php endif; ?>
  <form action="<?php echo $this->getUrl('newsletter/manage/save') ?>" method="post" id="form-validate">
    <fieldset>
        <?php echo $this->getBlockHtml('formkey')?>
        <p><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif ?> /> <label for="subscription"><?php echo $this->__('General Subscription') ?></label></p>
    </fieldset>
    <div class="button-set">
        <!--<a href="<?php //echo $this->getBackUrl() ?>" class="left">&laquo; <?php //echo $this->__('Back') ?></a>-->
        <button type="submit" class="form-button"><span><?php echo $this->__('Save') ?></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
<?php echo $this->getLayout()->getBlock("right.newsletter")->toHtml(); ?>
</ul>