<div class="box base-mini mini-news">
	<div class="head">
		<div class="content">
		<h4><?php echo $this->__('News') ?></h4>
		</div>
	</div>
	<div class="news-content">
		<ul class="news-list">
	<?php   
	  /*
	    This will load one record from your database table.
	    load(news_id) will load whatever ID number you give it.
	  */

	  /*
	    $news = Mage::getModel('news/news')->load(1);
	    echo $news->getNewsId();
	    echo $news->getTitle();
	    echo $news->getContent();
	    echo $news->getStatus();
	  */

	  /*
	  This block of code loads all of the records in the database table.
	  */

	    $collection = Mage::getModel('news/news')->getCollection();
	    $collection->setPageSize(5);
	    $collection->setCurPage(2);
	    $size = $collection->getSize();
	    $cnt = count($collection);
		$i = 1;
		foreach($collection as $s_item){
			if(!($s_item->getStatus())){
				$i++;
			}
		}
		$lNum = 2;
		?>
	    <?php foreach ($collection as $item):?> 
		<?php if($i >= $cnt-2 && $item->getStatus()): ?>
		<li id="l<?php echo $lNum; ?>">
					<div>
					<span class="title">
					<?php	$dateString = $item->getCreatedTime(); /* <- string: 2009-08-18 15:53:18 */?>
					<?php	$fullDateArray = split(' ', $dateString); ?>
					<?php	$dateArray = split('-', $fullDateArray[0]); ?>
					<?php	echo $dateArray[2].'/'.$dateArray[1].'/'.$dateArray[0].' - '.$item->getTitle() ?><br/>
					</span>
					<span class="content">
					<?php	echo $item->getContent() ?><br/>
					</span>
					</div>
		</li>
		<?php $lNum--; ?>
		<?php endif; ?>
		<?php $i++; ?>
	    <?php endforeach; ?>

	<?php
	/*
	    This shows how to load one value, change something and save it.
	  */

	  /*
	  $object = Mage::getModel('news/news')->load(1);
	  $object->setTitle('This is a changed title');
	  $object->save();
	  */
	?>
	</ul>
	</div>
</div>