

<?php 

    $tool = & $GLOBALS["magictoolbox"]["magiczoom"];

    if(!defined('__MAGICZOOM_INCLUDED')) {
        echo $tool->addonsTemplate($this->getSkinUrl('images'));
        define('__MAGICZOOM_INCLUDED',1);
    }
    
    $_product = $this->getProduct();
    
    //$allowedPage = $tool->params->checkValue('pages', array('Product', 'Both'));
    $allowedPage = $tool->params->checkValue('use_effect_on_product_page', 'Yes');
    
    if ($allowedPage && $_product->getImage() != 'no_selection' && $_product->getImage()) {
        // we have main image. parce it and print out with Magic Zoom settings.
        $title = $this->htmlEscape($_product->getName());
        $description = $this->htmlEscape($_product->getDescription());
        $shortDescription = $this->htmlEscape($_product->getShortDescription());
        
        if($tool->params->checkValue("caption_source", "Short description")) {
            $description = $shortDescription;
            $tool->params->set("caption_source", "Description");
        }
        
        if(!isset($GLOBALS["magictoolbox"]["image_num"])) $GLOBALS["magictoolbox"]["image_num"] = 1;
        $id = 'magictoolbox' . $GLOBALS["magictoolbox"]["image_num"]++;
        
        list($img, $thumb) = magicToolboxResizer($_product, 'image', $tool->params->getValue("thumb_size"));
        
        echo $tool->template(compact("id", "title", "description", "img", "thumb"));
        
    } else {
        //product has no main image. print magento default image
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($_product->getName()).'" />';
        echo $this->helper('catalog/output')->productAttribute($_product, $_img, 'image');
    }
    
    if (count($this->getGalleryImages()) > 1) {
        // print more images
        ?>
            <div class="more-views">
                <ul>
                    <?php 
                        $title = $this->htmlEscape($_product->getName());
                        foreach($this->getGalleryImages() as $_image) { 
                            if($allowedPage) {
                                list($img, $medium) = magicToolboxResizer($_product, 'image', $tool->params->getValue("thumb_size"), $_image->getFile());
                                list($img, $thumb) = magicToolboxResizer($_product, 'image', $tool->params->getValue("selector_size"), $_image->getFile());
                                if($tool->params->checkValue('use_individual_titles', 'Yes')) {
                                    $title = $this->htmlEscape($_image->getLabel());
                                }
                                if(empty($title)) {
                                    $title = $this->htmlEscape($_product->getName());
                                }
                                $a = $tool->subTemplate(compact("id", "img", "thumb", "medium", "title"));
                                $a = str_replace("<a ", "<a onclick=\"MagicToolbox_changeOption(this);\" ", $a);
                                if($tool->params->checkValue('ignore_magento_css', 'Yes')) {
                                    $a = str_replace("<a ", "<a style=\"width:auto; height:auto;\" ", $a);
                                }
                                echo "<li>{$a}</li>";
                            } else {
                                ?>
                                    <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=50,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                                <?php
                            }
                        }                        
                    ?>
                </ul>
            </div>
        <?php    
    }
?>
